CREATE TABLE "GCG_6300_IMPACTS" (
 "RECORD_NO" SMALLIDENTITY DEFAULT '0' CONSTRAINT "UK_RECORD_NO" UNIQUE USING 0,	
 "TYPE" CHAR(2),
 "CNTRL_NUM" CHAR(7),
 "CNTRL_SUF_LN" CHAR(4),
 "DATE_IMPACT" DATE,
 "IMPACT_REASON" CHAR(50),
 "DEPT_IMP_OWNER" CHAR(50),
 "USER_IMP_OWNER" CHAR(50),
 "IMPACT" LONGVARCHAR,
 "NEXT_STEP" LONGVARCHAR,
 "RESOLUTION" LONGVARCHAR,
 "DATE_CLOSED" DATE,
 "USER_CLOSED" CHAR(8) );